### ISSUE TITLE
Typescript can't find declaration folder because the name is wrong

### ISSUE THREAD

**Issue by tidurand** [barbajs/barba#739]
### What version are you using?

2.10.0

### What package are you using?

@barba/core

### Describe your issue

There is this issue "Could not find a declaration file for module '@barba/core'." with typescript

Because in package.json there is : "types": "dist/core/src/typings"
But currently the correct folder is : "types": "dist/core/src/src"

**Comment by xavierfoucrier** [comment]
Hello @tidurand 👋 

Thanks for getting in touch!
Looks like more an issue when publishing to NPM as well, this will be fixed in the next release.

> Keep this issue open as a reminder 😉

**Comment by CptCompiler** [comment]
Hi @xavierfoucrier,
seems that this has not yet been fixed in the current 2.10.2 version. 😟 
Any updates on this issue?
Thank you!

**Comment by xavierfoucrier** [comment]
@CptCompiler 👋 yup, I know, probably due to microbundle or lerna as well. Need to investigate.

**Comment by joshua-isaac** [comment]
any update on when this will get resolved?

**Comment by xavierfoucrier** [comment]
Hello, not critical currently, should be fixed soon, thanks!

**Comment by darcynoa** [comment]
Thought I'd bump this up as I understand that this is not critical, but just looking to see when this will be fixed. Just tried in NextJS and still getting this error 👍

**Comment by kurtiz** [comment]
I seem to have bumped into the same situation... Has anyone found a solution yet?

**Comment by xavierfoucrier** [comment]
Hello everyone,

Bug has already been fixed, but is not published currently.
I have to deal with new CI / tests issues, when it's done, a new version will be pushed to NPM.

> See https://github.com/barbajs/barba/issues/753#issuecomment-2553108878 for those who are working with NextJS or another JS framework.

**Comment by mogspls** [comment]
Any news on getting this resolved any time soon?

**Comment by xavierfoucrier** [comment]
@mogspls hi 👋,

Yup, it is still planned on my todolist 👌, but still have a high workload this past few months.
I will force myself to block a timespan for working on Open Source stuff soon.

Thanks again for your patience 🙏
